### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by Marlamin** [wowdev/Ribbit.NET#1]
Use already locally cached messages if available in C:\ProgramData\Battle.net\Agent\data\cache, not sure we're confident enough of actually writing our cache files there either so might be best to copy those to application dir for now or something. Probably best to also use the same naming method they use.

**Comment by Warpten** [comment]
i would avoid using that directory. they typically dont cleanup after themselves, but they might do it in the future. wouldn't want local cache to get wiped becaue you/we/whoever got lazy and used that directory. if anything just use symlinks

**Comment by Marlamin** [comment]
Fair argument, we probably still want to cache stuff though.
